name: Release to Maven Central

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build project
        run: ./gradlew build

      - name: Import GPG key
        run: |
          echo "$GPG_PRIVATE_KEY" > private.asc
          gpg --batch --import private.asc
          gpg --batch --yes --pinentry-mode loopback --passphrase "$GPG_PASSWORD" \
            --output secring.gpg --export-secret-keys "$GPG_KEY_ID"
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}

      - name: Publish to Maven Central
        run: |
          ./gradlew publishAndReleaseToMavenCentral \
            -Psigning.keyId=$GPG_KEY_ID \
            -Psigning.password=$GPG_PASSWORD \
            -Psigning.secretKeyRingFile=secring.gpg \
            -PmavenCentralUsername=$MAVEN_CENTRAL_USERNAME \
            -PmavenCentralPassword=$MAVEN_CENTRAL_PASSWORD \
            --no-configuration-cache
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}

      - name: Generate license report
        run: ./gradlew generateLicenseReport

      - name: Rename license report
        run: mv build/reports/dependency-license/index.html build/reports/dependency-license/dependencies_report_jvm.html

      - name: Upload artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/libs/*.jar
            build/libs/*.jar.asc
            build/reports/dependency-license/dependencies_report_jvm.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
