name: Publish Jar to GitHub Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build jar and artifacts
        run: ./gradlew build javadocJar sourcesJar generateLicenseReport

      - name: Rename license report
        run: mv build/reports/dependency-license/index.html build/reports/dependency-license/dependencies_report.html

      - name: Upload jar and license report to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/libs/*.jar
            build/reports/dependency-license/dependencies_report.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
